### ISSUE TITLE
Redirection après login

### ISSUE THREAD

**Issue by lucille-d** [Dexedrine/myteammate#11]
Je ne sais pas si j'ai créé le problème ou si il existait déjà, mais quand on accédait à la page de login manuellement (pas en voulant accéder à un profil), après connexion on n'était pas redirigés ce qui créait une erreur, j'ai résolu ça en modifiant le fichier security, mais j'ai du mettre en dur le nom du profil vers lequel on était redirigé.

Il y a donc un travail à faire sur cette redirection, voir pour lui passer le nom de l'utilisateur logué, éventuellement utiliser une autre méthode... 

En tout cas penser à ne pas laisser ça comme ça!

Si j'ai créé le problème d'une façon ou d'une autre, on pourra toujours annuler mon commit.

**Comment by lucille-d** [comment]
Plus vraiment valable au vu du dev d'anthony mais je laisse l'issue pour gérer le fait d'accéder à un autre profil que le sien.

**Comment by taoder** [comment]
Oui, j'ai vu que tu avais modifié le fichier security.yml. C'était exactement ça. J'ai changé la façon de gérer la sécurité, en ajoutant un user à chaque chemin on protège toute les pages avec juste une petite ligne de conf. 
Mais j'avais oublié de changer la redirection après le login_check. 

Je ferme l'issue puisque le fait de se connecter à la page profil suivant si on est ou pas sur sa propre page ne sera pas géré par la sécurité.
