### ISSUE TITLE
Gestion des boutons sur les côtés de la banderole. 

### ISSUE THREAD

**Issue by taoder** [Dexedrine/myteammate#12]
C'est bien ce que tu as fait pour gérer c'est deux bouton. On pourra comme ça dans chaque bundle choisir qu'elle bouton on souhaite mettre à droite et à gauche. J'ai d'ailleurs déjà utilisé celui de gauche pour ajouter un sport dans le SportBundle.

Par contre, si on prend en compte que ce site se retrouvera ensuite sur mobile, je pense qu'il sera possible d'ajouter un truc ou on trouve les paramètres avec un bouton logout. Au final c'est juste un lien je pense pas que ça soit compliqué. Je préfère garder une option pour retour sur la page d'accueil par exemple.

Mais sinon je pense que tu as raison pour le moment c'est pas mal d'avoir un lien pour se déconnecter.

**Comment by lucille-d** [comment]
Je pense que ça n'a plus lieu d'être ouvert, le truc d'anthony est pas mal :)
