### ISSUE TITLE
Encodage

### ISSUE THREAD

**Issue by lucille-d** [Dexedrine/myteammate#16]
Je ne sais pas vous, mais quand j'accède à la page de login, les accents ne passent pas, j'imagine que c'est vrai pour tout le site:
"Rester connect�"

Pourtant le charset est bien là dans le head et les fichiers sont bien encodés en utf8. J'ai cherché un peu et trouvé des trucs pour configurer apache directement pour qu'il serve par défaut de l'utf8 mais rien n'y fait.

Avez-vous tous le problème? Avez-vous des solutions?^^

PS: Un commit pas fini n'est pas un commit... A moins de devoir passer la main à quelqu'un

**Comment by Dexedrine** [comment]
J'ai eu un gros soucis avec eclipse pour les commit donc j'ai été obligé de
le passer comme ça.

**Comment by Dexedrine** [comment]
J'ai modifié le code pour l'affichage de l'accent
