### ISSUE TITLE
CSS

### ISSUE THREAD

**Issue by Dexedrine** [Dexedrine/myteammate#17]
style.css n'est plus dans mon projet. Pareil pour vous ? Est-ce que ça a un lien quelconque avec les assets ?

**Comment by taoder** [comment]
Oui, il se trouve dans le dossier Ressource/public du DesignBundle, c'est le seul moyen trouvé pour qu'il soit mis en prod proprement. Sans avoir à faire des magouille.

**Comment by lucille-d** [comment]
ll est dans le bundle Design c'est pour la publication des assets, il ne doit plus revenir dans app!
