### ISSUE TITLE
Framework CSS

### ISSUE THREAD

**Issue by taoder** [Dexedrine/myteammate#18]
Vous allez penser que je suis lourd avec ça mais cette idée d'avoir un framework CSS met rentré dans la tête. J'ai commencé à faire des recherches pour voir se qu'on pouvait trouvé.

J'ai directement supprimer les framework les plus connues (bootstrap, foundation, jquery UI/mobile) qui sont lourd et très peu personnalisable avec eux on va se retrouver avec un site comme tout les autres.

Du coup j'ai étendu mes recherches à des framework plus légers qui offrent une base et ensuite on peut créer un peu se qu'on veut. Je vous mets les liens juste en dessous : 
- https://github.com/csswizardry/inuit.css
- http://rocssti.nicolas-hoffmann.net/
- http://www.knacss.com/

Voilà, si vous en trouvez d'autre. Ou si vous n'aimez pas du tout l'idée, d'avoir un peu d'aider sans avoir un site clone.

**Comment by taoder** [comment]
Je clos cette issue, on part sans framework. On fait des trucs supers beaux sans.

**Comment by Dexedrine** [comment]
On vient de me montrer ça : http://960.gs/
En gros, ce serait pour avoir une uniformité au niveau des tailles qu'on utilise. La partie http://grids.heroku.com/ est faite pour ça. Par exemple, on fait 4 colonnes séparées de x px, on génere (preview avant) et on voit les balises a appeler.
Et apparement il y a une partie responsive : http://adapt.960.gs/

Et il semblerait que bootstrap utilise le même principe. A voir
