### ISSUE TITLE
alias pratiques

### ISSUE THREAD

**Issue by lucille-d** [Dexedrine/myteammate#20]
Vous y avez peut-être déjà pensé et je suis la dernière con-con à le faire, mais dans le doute je partage^^ j'ai ajouté quelques alias pratiques à mon bashrc pour éviter de rechercher les commandes à chaque fois:
# projet myteammate

alias mtm='cd /cygdrive/c/BitNami/wappstack-5.4.12-0/project/myteammate/MyTeamMate/'
alias assets='php app/console assets:install web --symlink'
alias mep='php app/console cache:clear --env=prod'
alias bdd='php app/console doctrine:schema:update --force'

(attention à adapter le chemin à votre arbo)

**Comment by taoder** [comment]
Je déplace la aussi dans le wiki.
