### ISSUE TITLE
Les icones sur MTM

### ISSUE THREAD

**Issue by Dexedrine** [Dexedrine/myteammate#21]
A la place de mettre plein d'image sur le site, j'utilise : http://icomoon.io/app/

Marche à suivre 
1.  Choisir vos icones ( ATTENTION il faut TOUJOURS reprendre celles qui ont déja été prise, sinon elles ne seront plus présentes pour les personnes ayant deja utilisé les icones) - peut etre se faire une liste générale une bonne fois pour toute avec toutes les icones pouvant etre utilisées
2. Download (ne pas enregistrer dans le projet MTM)
3. Dézipper le ficher
4. Renommer style.css en icon.css
5. Copier tout SAUF licence et index.html
6. Coller les fichiers dans ressources/public/css
7. Le css est déjà inclut dans le template de base (raison pour laquelle il faut renommer le fichier en icon.css et reprendre toutes les icones deja existantes)
8. Les icones ont été "transformé" en font, pour les utiliser par exemple :                  <span class="icon" data-icon="&#xe000;" aria-hidden="true" title="username"></span>

Il faut ajouter data-icon et aria-hidden.
Le nom de toutes les icones se trouve dans le fichier index.html

Si vous avez des questions hésitez pas !

**Comment by taoder** [comment]
Je déplace aussi. ^^

**Comment by Dexedrine** [comment]
Si vous avez besoin d'icones du site, dites moi lesquelles (exemple l'icone 5 ligne 3 de la partie Iconic, fastidieux certes mais au moins pas d'icones qui se perdent).
Je me chargerai de les télécharger et de les integrer au projet en vous fournissant les codes pour chaque icones.

Je reouvre l'issue, on la fermera la prochaine fois qu'on se voit pour etre sur que tout le monde est ok :)
