### ISSUE TITLE
Design de la page registration

### ISSUE THREAD

**Issue by Dexedrine** [Dexedrine/myteammate#22]
Je m'occupe de cette page. Le design sera le mm que la page de login pour garder une cohérence globale de l'appli

**Comment by taoder** [comment]
Personnellement ça me va. J'aime beaucoup la page de login. Par contre ça veut dire qu'il faudra utilisé ça pour le reste de nos formulaires. Ça risque d'être rébarbatif, non?

Lorsque j'ai fait la page registration, j'ai pas doublé les champs email(je sais pas si c'est utile) et mot de passe et aussi ajouter un contrôle avec js pour vérifier que les champs soit égaux avant qu'il valide le formulaire. Plus on en fait côté client et moins on a de trafic réseau. Si tu veux, je peux m'en occuper, mais je pense que tu vas avoir envie de faire autre chose du CSS.

**Comment by gzk** [comment]
je pense que doubler le champs email ça ne sert à rien par contre mot de passe je suis d'accord

**Comment by taoder** [comment]
Si une personne se trompe dans son adresse, elle ne recevra pas son mail de validation donc ne l'acceptera pas. Je propose donc d'ajouter des tâches qui supprimerons les personnes n'ayant pas validé leur compte au bout d'un certain temps. Vous en pensez quoi ?

**Comment by gzk** [comment]
je suis d'accord

**Comment by Dexedrine** [comment]
Oui c'est une bonne idée pour la suppression des gens qui n'ont pas validé.
J'pense qu'il faudrait qu'on refasse un point pour savoir où on en est. On
peut faire ça dans un google doc histoire de pas recevoir un mail à chaque
changement de virgule. Non ?

2013/4/15 gzk notifications@github.com

**Comment by taoder** [comment]
Ok, on passe sur google doc. On mettra en page correctement. On pourra comme ça s'en servir de rapport d'avancement et le rajouter au wiki.
