### ISSUE TITLE
Design général

### ISSUE THREAD

**Issue by Dexedrine** [Dexedrine/myteammate#23]
Voici une liste de site referençant de multiples design d'appli mobiles. J'ai trouve le style de la page login sur ces sites
http://www.mobile-patterns.com/
http://dribbble.com/
http://www.lovelyui.com/
http://www.mobiledesignpatterngallery.com/mobile-patterns.php
http://pttrns.com/categories/3-comments
http://androidpttrns.com/

Enjoy !

**Comment by taoder** [comment]
Je déplace ça dans le wiki.
