### ISSUE TITLE
Gestion d'erreur page de login.

### ISSUE THREAD

**Issue by taoder** [Dexedrine/myteammate#25]
Il faudrait qu'il y est d'autre message lorsqu'on se trompe de mot de passe. Parce que bad credential, c'est pas terrible. ^^ 

Je pense que tu ais la mieux placer pour t'en occuper.

**Comment by taoder** [comment]
On en discute dans le google doc.

**Comment by Dexedrine** [comment]
Oublie pas de partager le google doc :)

2013/4/16 taoder notifications@github.com
