### ISSUE TITLE
Redirection page login.

### ISSUE THREAD

**Issue by taoder** [Dexedrine/myteammate#26]
Je vais faire en sorte qu'une personne connectée soit redirigée sur la page de profil si il tente d'atteindre la page de login.

**Comment by taoder** [comment]
C'est fait.

**Comment by gzk** [comment]
Tu as commité ? 
Car chez moi ça ne fonctionne pas

**Comment by gzk** [comment]
après correction d'un problème(de mon côté) cela fonctionne, désolé d'avoir mis en cause ton travail

**Comment by taoder** [comment]
T'inquiète l'autre jour j'ai accusé quelqu'un d'avoir tout cassé et c'était moi en faite. ^^
