### ISSUE TITLE
Petite précision au sujet des icônes

### ISSUE THREAD

**Issue by taoder** [Dexedrine/myteammate#27]
Un moment tu parles d'ajouter data-icon et aria-hidden. 

Ça veut dire quoi ? 

Merci

**Comment by Dexedrine** [comment]
C'est juste comme ça qu'on les utilise. Rien de plus à savoir je pense. Tu peux toujours regarder dans la doc du site, il y a peut etre plus d'infos :)

**Comment by taoder** [comment]
C'était pas ça ma question, c'est juste ou il faut les ajouter.

**Comment by Dexedrine** [comment]
On les utilise comme si c'était des attributs de ta balise
Exemple : span class="icon" data-icon="&#xe000;" aria-hidden="true" title="username"></span

**Comment by gzk** [comment]
"Exemple : " ?

**Comment by Dexedrine** [comment]
Tu peux aller le voir dans le code aussi. La balise span n'est pas passé, j'ai enlevé les deux <> pour qu'elle passe

**Comment by gzk** [comment]
Merci

**Comment by taoder** [comment]
Ok, je vais ajouter dans le wiki. Merci.
