### ISSUE TITLE
Border-radius

### ISSUE THREAD

**Issue by taoder** [Dexedrine/myteammate#28]
Etant donnée que nous sommes parti dans l'idée de tuile carré. Je pense qu'il est une bonne idée de bannir les border-radius de la surface du site jusqu'en profondeur.  

@Dexedrine  Ça n'enlève rien au design de ta page de login au contraire. (enfin question de point de vue)

Vous en pensez quoi ?

**Comment by Dexedrine** [comment]
D'accord pour enlever les border-radius pour garder une identité graphique pour tout le site :)
