### ISSUE TITLE
insertion en base KO

### ISSUE THREAD

**Issue by Dexedrine** [Dexedrine/myteammate#29]
L'insertion en base depuis /registration est KO

**Comment by gzk** [comment]
je regarde ça ce soir

**Comment by gzk** [comment]
je n'ai pas réussi à corriger le problème

**Comment by Dexedrine** [comment]
Est-ce que le problème vient de la modification + regeneration de la base
ou de mes modifs css ?
Si qqn n'a pas encore pushé mes modifs, est-ce qu'il peut faire les manip
sur la base et vérifier que tout fonctionne encore ?

2013/4/29 gzk notifications@github.com

**Comment by lucille-d** [comment]
J'ai résolu le problème. Explications demain :)
