### ISSUE TITLE
Relecture et précision de l'analyse fonctionnelle

### ISSUE THREAD

**Issue by taoder** [Dexedrine/myteammate#3]
J'ai essayé de faire au mieux surement des incohérences. Si tu peux prendre 10-15 minutes pour la relire et ajouter des trucs peut être.

A chaque fois je répète ce qu'est le module et ensuite ce qu'il va falloir faire pour le mettre en place. 

Je pense que pendant la pause du midi on aura le temps d'y regarder pour finioler.

**Comment by taoder** [comment]
Pourras tu ajouter l'analyse fonctionnelle à github? Merci.

**Comment by lucille-d** [comment]
Fait! Liens de tous les google docs sur la home page du wiki (plus pratique que de créer les pages à chaque fois)
