### ISSUE TITLE
Images partie message

### ISSUE THREAD

**Issue by gzk** [Dexedrine/myteammate#35]
Peux tu vérifier que j'ai mis les bons codes pour les images dans la barre de menu de la partie message, car là ça ne fonctionne pas.
Dans le fichier => /MyTeamMate/src/MTM/MessageBundle/Resources/views/layout.html.twig

**Comment by Dexedrine** [comment]
Problème réglé, c'etait un problème de copier/coller. J'avais remplacer un dossier mais ça ne l'a pas écrasé mais mis dans un sous répertoire
