### ISSUE TITLE
Charte graphique

### ISSUE THREAD

**Issue by lucille-d** [Dexedrine/myteammate#5]
Il serait probablement temps de commencer à penser à une charte graphique, au moins quelques couleurs dominantes, et dans le meilleur des cas un logo, histoire de donner un peu de personnalité à notre présentation du 14/02.

Je suis loin d'être doué dans ce domaine mais quand je m'imagine l'appli je la vois rouge. C'est un début, non?^^

Enfin sujet ouvert à la discussion, avec google doc à la clé :)
https://docs.google.com/document/d/16MmObHYhS2j6PxRkzUv6YQZ5V2hfN-uUNXpQsTWzHRY/edit?usp=sharing 
Je ne le partage pas tout de suite avec Marius, c'est plus un espace de discussion qu'un livrable.

**Comment by lucille-d** [comment]
Première réflexion sur la charte graphique: https://docs.google.com/document/d/16MmObHYhS2j6PxRkzUv6YQZ5V2hfN-uUNXpQsTWzHRY/edit?usp=sharing

**Comment by Dexedrine** [comment]
A la vue des premiers rendus graphique je suis plus ouverte à  un changement de couleur :)
