### ISSUE TITLE
Arborescence

### ISSUE THREAD

**Issue by lucille-d** [Dexedrine/myteammate#6]
Hello,

Je pense qu'il faut qu'on se fasse un point, pendant l'heure de projet ou en dehors, concernant l'arborescence des fichiers, des projets, etc... Parce que là sur github il y a phonegap si je comprends bien, mais qu'en est-il du projet PHP, comment il s'intègre à ça, est-ce un projet à part?

Je ne m'y retrouve pas bien et je pense qu'il faudrait mettre tout ça à plat. Je m'apprête à bosser sur ma page html et je voulais la commiter pour que tout le monde puisse la voir, mais finalement je vais m'abstenir :) 

Je te l'assigne parce qu'à priori tu es celui qui sait le mieux, mais je pense que ça intéresse tout monde.

**Comment by taoder** [comment]
Nous avons fait le point lors d'une réunion sur ce sujet, j'ai ajouté une page avec l'arborescence des bundles dans le wiki.
