### ISSUE TITLE
Modification dans le code

### ISSUE THREAD

**Issue by taoder** [Dexedrine/myteammate#9]
Une fois que vous aurez puller et re-générer les base de donnée. Il vous est possible de tester les améliorations que nous avons apporté avec Lucille cette après midi. 

Pour cela, après avoir démarrer vos serveur bien sur, entrez l'adresse suivant dans un navigateur : 

http://localhost:8080/myteammate/app_dev.php/profile/lala

("lala" peut être remplacé par ce que vous voulez)

Nous vous expliquerons lors de notre prochaine réunion ce qui se passe derrière. Bien sur l'explication sera plus facile si de votre côté vous avez réalisé les tutos.

**Comment by Dexedrine** [comment]
Lien plus valide aux vues des dev qui ont été fait ce week-end.
